feat(plugin-calendar): Decrypt mercury calendar events
saurjai3/spark-js-sdk pull request #4
Opened 2017-05-04 18:02 UTC by urbenlegend

PR to get mercury calendar events properly decrypting in SDK.

Still need to write a mercury test for this but wanted to submit this PR for review first

@saurjai3 @ianwremmel

2017-05-04 18:49 UTC, ianwremmel requested changes

2017-05-04 18:49 UTC, ianwremmel commented on packages/node_modules/@ciscospark/plugin-calendar/src/index.js
> +        name: `transformMeetingFromMercury`,
This should be achievable without a new transformation. this predicate should be also be named `tranformMeeting`, but should provide a different `extract()` than the `transformMeeting` above.

2017-05-04 21:14 UTC, urbenlegend commented on packages/node_modules/@ciscospark/plugin-calendar/src/index.js
> +        name: `transformMeetingFromMercury`,
Ah that makes sense. Done.

2017-05-04 23:25 UTC, ianwremmel requested changes
Can this be tested?

2017-05-04 23:29 UTC, urbenlegend commented
Yes, I am writing a test now. Getting issues where I am not getting a mercury response back. Looking into it.

2017-05-04 23:51 UTC, ianwremmel requested changes

2017-05-04 23:51 UTC, ianwremmel commented on packages/node_modules/@ciscospark/plugin-calendar/test/integration/spec/calendar.js
> +    before(`create test users and initialize spark`, () => testUsers.create({
I would break this into multiple named before blocks. that makes it a lot easier to debug issues in jenkins.

2017-05-04 23:51 UTC, ianwremmel commented on packages/node_modules/@ciscospark/plugin-calendar/test/integration/spec/calendar.js
> +        mercuryPromise = new Promise((resolve) => {
This should probably go in the `it` blocks

2017-05-04 23:51 UTC, ianwremmel commented on packages/node_modules/@ciscospark/plugin-calendar/test/integration/spec/calendar.js
> +      return assert.isFulfilled(mercuryPromise)
How does the meeting get created?

2017-05-05 04:17 UTC, urbenlegend commented
Comments have been addressed @ianwremmel

2017-05-08 23:47 UTC, ianwremmel requested changes

2017-05-08 23:47 UTC, ianwremmel commented on packages/node_modules/@ciscospark/plugin-calendar/test/integration/spec/calendar.js
> +  describe(`list meeting`, () => {
Why the name change here? describe blocks should typically adhere to the form:

```js
describe(`<plugin name>`, () => {
  describe(`<class name>`, () => {
    describe(`#<function name>()`, () => {
    });
  });
});
```

so, these tests should be under

```js
describe(`plugin-calendar`, () => {
  describe(`Calendar`, () => {
    describe(`#list()`, () => {
    });
  });
});
```

2017-05-08 23:53 UTC, urbenlegend commented on packages/node_modules/@ciscospark/plugin-calendar/test/integration/spec/calendar.js
> +  describe(`list meeting`, () => {
Okay, I'll change it back.

2017-05-08 23:54 UTC, ianwremmel commented on packages/node_modules/@ciscospark/plugin-calendar/test/integration/spec/calendar.js
> +  describe(`list meeting`, () => {
Note that it's actually always been missing a level.

2017-05-09 00:02 UTC, urbenlegend commented on packages/node_modules/@ciscospark/plugin-calendar/test/integration/spec/calendar.js
> +  describe(`list meeting`, () => {
Fixed

2017-05-09 00:24 UTC, ianwremmel approved these changes

2017-05-09 00:30 UTC, urbenlegend commented
Thanks for the review @ianwremmel!

2017-05-19 23:17 UTC, closed without merging